import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/utils/redux/reduxProvider";
import { ToastContainer } from "react-toastify";
import Topbar from "@/components/Topbar/Topbar";
import Navbar from "@/components/Navbar/Navbar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Al-Shafi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <ReduxProvider>
          <>
            <Topbar />
            <Navbar />
          </>
          {children}
        </ReduxProvider>
        <ToastContainer position="top-center" />
      </body>
    </html>
  );
}
